require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0

# Exclude comments for LineLength style
Metrics/LineLength:
  IgnoredPatterns: ['(\A|\s)#']
