development: &defaults
  adapter: postgresql
  min_messages: warning
  host: epi-stu-gen-dbs1-pg.shef.ac.uk
  username: acb16jhn
  password: '25ca4a757116b1abde87af261f614c2d'
  database: acb16jhn_dev1

test:
  <<: *defaults
  database: acb16jhn_test
