development:
  adapter: postgresql
  database: project_dev
  host: ''
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: project_test
  host: ''
  min_messages: warning
  username:
